### ISSUE TITLE
Create CSS file 

### ISSUE THREAD

**Issue by Ashleighjg** [MrGithubby/MusicBoxProject#8]
Add accessible styling and design layout to the MusicBox App

**Comment by AndrewBrown77** [comment]
use story:
as a user i would like a styled CSS page that is linked correctly

**Comment by MrGithubby** [comment]
Comment from Daler: Break this up

**Comment by MrGithubby** [comment]
@AndrewBrown77 Can you please copy the PR and post a screenshot of the app before marking this as approved

**Comment by AndrewBrown77** [comment]
Images of addition below :

![Image](https://github.com/user-attachments/assets/46d43343-8d71-4e8c-b32f-47b96bf6d70f)



![Image](https://github.com/user-attachments/assets/d5b660dd-3271-4552-9d73-bfc96902fcde)
